--====================================
--DATABASE SCHEMA FOR WORK LOG
--====================================

-- SQL Script: WorkLog Tables
CREATE TABLE WorkLogEntries (
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
RequirementId UNIQUEIDENTIFIER NOT NULL,


-- User Information
UserId NVARCHAR(255) NOT NULL,
UserName NVARCHAR(255) NOT NULL,
UserEmail NVARCHAR(255),
UserAvatar NVARCHAR(500),

-- Action Information
Action NVARCHAR(100) NOT NULL,           -- status_changed, deadline_updated, comment_added, etc.
Category NVARCHAR(50) DEFAULT 'General', -- General, System, Workflow, Calendar, etc.
Description NVARCHAR(MAX) NOT NULL,      -- Human readable description

-- Change Tracking
FieldName NVARCHAR(100),                 -- Which field was changed
OldValue NVARCHAR(MAX),                  -- Previous value (JSON or string)
NewValue NVARCHAR(MAX),                  -- New value (JSON or string)

-- Additional Context
WorkflowStep NVARCHAR(100),              -- Current workflow step
ClientInfo NVARCHAR(MAX),                -- Browser/IP info (JSON)

-- Time Tracking
TimeSpent INT DEFAULT 0,                 -- Minutes spent on this action

-- Metadata
CreatedAt DATETIME2 DEFAULT GETDATE(),
IsSystemGenerated BIT DEFAULT 0,         -- Was this generated by system vs user
IsPublic BIT DEFAULT 1,                  -- Should this be visible to all users

-- Soft Delete
IsDeleted BIT DEFAULT 0,
DeletedAt DATETIME2,
DeletedBy NVARCHAR(255),

-- Indexes
INDEX IX_WorkLogEntries_RequirementId (RequirementId),
INDEX IX_WorkLogEntries_UserId (UserId),
INDEX IX_WorkLogEntries_Action (Action),
INDEX IX_WorkLogEntries_CreatedAt (CreatedAt),
INDEX IX_WorkLogEntries_Category (Category),
INDEX IX_WorkLogEntries_Timeline (RequirementId, CreatedAt, IsDeleted),

-- Foreign Key
FOREIGN KEY (RequirementId) REFERENCES Requirements(Id) ON DELETE CASCADE


);

-- Work Log Attachments (for screenshots, documents, etc.)
CREATE TABLE WorkLogAttachments (
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
WorkLogEntryId UNIQUEIDENTIFIER NOT NULL,


-- File Information
FileName NVARCHAR(255) NOT NULL,
OriginalFileName NVARCHAR(255) NOT NULL,
FileSize INT NOT NULL,
ContentType NVARCHAR(100) NOT NULL,

-- Storage
StoragePath NVARCHAR(500),
StorageType NVARCHAR(50) DEFAULT 'FileSystem',

-- Metadata
UploadedAt DATETIME2 DEFAULT GETDATE(),

-- Indexes
INDEX IX_WorkLogAttachments_WorkLogEntryId (WorkLogEntryId),

-- Foreign Key
FOREIGN KEY (WorkLogEntryId) REFERENCES WorkLogEntries(Id) ON DELETE CASCADE


);
